EPT-2389: adds event on click to clear previous selected file
ePages-de/beyond_canvas pull request #111
Opened 2023-04-04 13:07 UTC by citin

## Task
Unexpected behaivor when loading a file with the same name twice. 

## Solution
Clear file input fields on click and tigger the change event to setup the view.
This change affects that if you click the input to upload a file but you cancel it, you will loose the previous file. This is the default expected behaviour of `html`.

## Usage
To add this behaviour to the input field you should add the `data-clear-on-click="true"` attribute to the html element. `f.file_field :images, data: { clear_on_click: true }` in RoR.

2023-04-12 07:41 UTC, citin commented on app/assets/javascripts/beyond_canvas/base.js
> -          if (fileName) $label.html('<svg class="input__file__icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M15 2v5h5v15h-16v-20h11zm1-2h-14v24h20v-18l-
Moves the svg icon to a vaiable `svgFileIcon `

2023-04-12 07:41 UTC, citin commented on app/assets/javascripts/beyond_canvas/base.js
> -        var labelVal = $label.html();
default value is stores in html attribute `data-no-file-text`

2023-04-12 08:06 UTC, gersanco requested changes

2023-04-12 08:06 UTC, gersanco commented on app/javascript/beyond_canvas/initializers/inputs.js
> +      this.files = dt.files;
Please let an empty line between `const dt = new DataTransfer();` and `this.files = dt.files;` to separate [declaration and logic](https://javascript.info/coding-style)

2023-04-12 08:10 UTC, gersanco commented
> This change affects that if you click the input to upload a file but you cancel it, you will loose the previous file. This is the default expected behaviour of html.

Maybe  we can add by default that data attribute for input files what do you think @unabris ?

2023-04-12 08:39 UTC, gersanco commented
> > > This change affects that if you click the input to upload a file but you cancel it, you will loose the previous file. This is the default expected behaviour of html.
> > 
> > 
> > Maybe we can add by default that data attribute for input files what do you think @unabris ?
> 
> Not sure about that. It's kind of a big change that will affect ALL file inputs. We'll need to be extremely careful for not breaking any existing logic.

But what about having that as default just for "files" nor "images" and if you don't need it you can add that attribute as false.

2023-04-12 09:12 UTC, gersanco approved these changes

2023-04-19 10:02 UTC, unabris approved these changes

2023-05-02 07:44 UTC, merged